apiVersion: v1
kind: Pod
metadata:
  name: events
  labels:
    name: events
spec:
  containers:
  - name: events
    image:  774440115756.dkr.ecr.eu-west-1.amazonaws.com/events:v1
    ports:
    - containerPort: 3000
