apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-deployment
  labels:
    app: events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events
  template:
    metadata:
      labels:
        app: events
    spec:
      containers:
      - name: events
        image: 774440115756.dkr.ecr.eu-west-1.amazonaws.com/events:v1
        ports:
        - containerPort: 3000
