apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: ecommerce-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-api
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      containers:
      - name: database
        image:  982606647141.dkr.ecr.eu-west-1.amazonaws.com/database:v1
        ports:
        - containerPort: 27017
