apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    name: database
spec:
  containers:
  - name: database
    image:  982606647141.dkr.ecr.eu-west-1.amazonaws.com/database:v1
    ports:
    - containerPort: 27017
