apiVersion: v1
kind: Pod
metadata:
  name: products
  labels:
    name: products
spec:
  containers:
  - name: products
    image: 774440115756.dkr.ecr.eu-west-1.amazonaws.com/products:v1
    ports:
    - containerPort: 3000
