apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: ecommerce-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-api
  template:
    metadata:
      labels:
        app: ecommerce-api
    spec:
      containers:
      - name: products
        image: 774440115756.dkr.ecr.eu-west-1.amazonaws.com/products:v1
        ports:
        - containerPort: 3000
